### ISSUE TITLE
Buscar Producto

### ISSUE THREAD

**Issue by carlosmding** [carlosmding/Joyeria_Back_End#13]
Como administrador quiero buscar productos para hacer gestión de estos

Dado que el administrador están en el formulario de productos
Cuando buscar un producto por nombre
Luego se muestra los productos que cumplen con los criterios de búsqueda

**Comment by Neltrin22** [comment]
Criterios de aceptación:
1. el usuario debe tener la opción de ingresar un nombre de producto a buscar
2. solo se puede ingresar un producto a la vez
3. si el producto no se encuentra en la base de datos se debe mostrar un mensaje de item no encontrado
4. si el producto se encuentra en la base de datos se debe mostrar la información de este
