### ISSUE TITLE
Eliminar producto

### ISSUE THREAD

**Issue by carlosmding** [carlosmding/Joyeria_Back_End#15]
Como administrador quiero eliminar un producto para que no sea ordenado

**Comment by Neltrin22** [comment]
Criterios de aceptación:
1.  El Administrador debe tener la opción de seleccionar el producto que desea eliminar.
2.  El administrador debe tener la opción por medio de un control para eliminar el producto selecionado.
3.  Se le debe confirmar al administrador que el producto fue borrado
