### ISSUE TITLE
Crear Producto

### ISSUE THREAD

**Issue by carlosmding** [carlosmding/Joyeria_Back_End#7]
**Como administrador quiero crear productos para hacer gestión de estos**

Dado que el administrador están en el formulario de productos
Cuando diligencia las características del producto y le da guardar
Luego el producto queda creado correctamente.

**Comment by Neltrin22** [comment]
Critrerios de aceptación:
1. El administrador agregar un nuevo producto indicandole su nombre
2. no puede ingresarse productos con el mismo nombre
3. debe haber un espacio para ingresar las caracteristicas del producto
4. despues de agregar la información debe estar habilitado un control para guardar
